### ISSUE TITLE
AppData doesn't meet requirements

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.jonathankang.Weibird#1]
The appdata doesn't meet the requirements, so the app doesn't show in the app store.

https://github.com/flathub/flathub/wiki/AppData-Guidelines

* The id is wrong, it should be `com.jonathankang.Weibird` not `com.jonathankang.Weibird.dekstop`
* The appdata is missing a launchable of `com.jonathankang.Weibird.dekstop`
* There's no screenshot
* There's no OARS tag

**Comment by JonathanKang** [comment]
Should be fixed in commit 45c6d066c60e78b6436b4b29495d07cbf159f5e5.

**Comment by JonathanKang** [comment]
Can I use a specific commit as the release in Flathub? In which way I don't have to make a new version release for such a specific fix.

**Comment by JonathanKang** [comment]
Fixed in the latest 0.1.4 release. And the build succeed as well: https://flathub.org/builds/#/builders/32/builds/967
